language: php

sudo: false

cache:
    directories:
    - $HOME/.composer/cache/files

php:
  - 7.4

install:
  - composer install --prefer-dist

script:
  - php bin/phpstan analyse -l 5 -c phpstan.neon src
  - bin/php-cs-fixer fix --dry-run -v --using-cache=no